[package]
name = "disjoint_impls"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/mversic/disjoint_impls"
description = "Support for a variety of mutually disjoint implementations"
keywords = ["disjoint", "exclusive", "associated", "impl", "implementation"]

[lib]
proc-macro = true

[dependencies]
syn = {version = "2.0.14", features = ["full", "extra-traits", "visit", "visit-mut"]}
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.56"
rustc-hash = "1.1.0"
quote = "1.0.26"
